### PR TITLE
web/forms: typed field parsers using generics

### PR DESCRIPTION
**Pull request by amery**
### **PR Type**
Enhancement, Tests

___

### **Description**
- Introduced generic parsers and formatters for signed, unsigned, float, and boolean types.
- Added functions to read and trim form values and post form values, including support for multiple values.
- Implemented generated code for parsing within specified ranges and for various types.
- Added shell scripts to automate the generation of parsing and formatting code.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>strconv.go</strong><dd><code>Add generic parsers and formatters for various types</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

web/forms/strconv.go

<li>Introduced generic parsers for signed, unsigned, float, and boolean <br>types.<br> <li> Added formatters for signed, unsigned, and float types.<br> <li> Implemented utility functions for bit size calculation and range <br>errors.<br>

</details>

  </td>
  <td><a href="https://github.com/darvaza-proxy/x/pull/51/files#diff-987ad1ce99087f025046ec55acfc0bf53f79a2eb2941c793cad3f36ce85d7db5">+76/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>strconv_gen.go</strong><dd><code>Add generated code for range-based parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

web/forms/strconv_gen.go

<li>Added generated code for parsing signed, unsigned, and float types <br>within specified ranges.<br>

</details>

  </td>
  <td><a href="https://github.com/darvaza-proxy/x/pull/51/files#diff-8ff89e68c44b37111ff42ff440477006acd3a50733b8f736d5d22e1ecf5343e3">+45/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>value.go</strong><dd><code>Add functions to read and trim form values</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

web/forms/value.go

<li>Introduced functions to read and trim form values and post form <br>values.<br> <li> Added support for reading multiple values and omitting empty ones.<br>

</details>

  </td>
  <td><a href="https://github.com/darvaza-proxy/x/pull/51/files#diff-14977439ebc6755cfa0aa15d949a5821cebdccc5052874365731666a47fb6d48">+74/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>value_gen.go</strong><dd><code>Add generated code for form value parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

web/forms/value_gen.go

<li>Added generated code for reading and parsing form and post form values <br>for various types.<br> <li> Included range-based parsing for ordered types.<br>

</details>

  </td>
  <td><a href="https://github.com/darvaza-proxy/x/pull/51/files#diff-b0859517eb6e2dec2d6277095939368106155989e832c9519aba056962c84593">+431/-0</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>strconv_gen.sh</strong><dd><code>Add script for generating range-based parsing code</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

web/forms/strconv_gen.sh

<li>Script to generate code for parsing signed, unsigned, and float types <br>within specified ranges.<br>

</details>

  </td>
  <td><a href="https://github.com/darvaza-proxy/x/pull/51/files#diff-feaa1f3baa038d9a1c9b07e676e8db6bd8906539b932cdb10ec4a56179771803">+69/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>value_gen.sh</strong><dd><code>Add script for generating form value parsing code</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

web/forms/value_gen.sh

<li>Script to generate code for reading and parsing form and post form <br>values for various types.<br> <li> Included range-based parsing for ordered types.<br>

</details>

  </td>
  <td><a href="https://github.com/darvaza-proxy/x/pull/51/files#diff-c045caeee6897b247668a7c0081fdbd359aaa0e6266601f7a2e86e709f6e47d1">+141/-0</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by amery** [comment]
on hold waiting for https://github.com/darvaza-proxy/core/pull/63

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
`darvaza.org/z/web@v0.6.5` tagged

**Review by karasz — COMMENTED** [review]
LGTM a second time?

**Pull request merged**
