### PR TITLE
fs: introduce Split()

### PR DESCRIPTION
**Pull request by amery**
`fs.FS` oriented `path.Split`

### CODE REVIEW

**Review by karasz — APPROVED** [review]
LGTM

**Review by karasz — COMMENTED** [review]
On second thoughts....

**Comment by amery** [comment]
As discussed privately `fs.FS` is `/` only and intentionally independent from the OS's delimiter. we should add in future a slim `osfs` implementation allowing use to work in full with the local filesystem using the `fs` interface

**Comment by amery** [comment]
`darvaza.org/x/fs@v0.1.1` tagged

**Pull request merged**
