### PR TITLE
container/set: introduce programmatic generic Set type

### PR DESCRIPTION
**Pull request by amery**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new `Config` struct for managing generic sets with callback functions.
	- Added a `Set` data structure with methods for adding, retrieving, and removing entries.
	- Implemented cloning and copying functionality for sets.
	- Added methods for retrieving values and iterating over them in a set.

- **Bug Fixes**
	- Enhanced error handling for set operations, including checks for existing and non-existent entries.

### CODE REVIEW

**Review by karasz — APPROVED** [review]
LGTM, although I would have liked to see an `Exists` method, but `Get` will do.

**Comment by amery** [comment]
> LGTM, although I would have liked to see an `Exists` method, but `Get` will do.

I have a Contains in the queue that basically wraps Get

**Comment by amery** [comment]
`darvaza.org/x/container@v0.1.1` tagged

**Comment by amery** [comment]
> LGTM, although I would have liked to see an `Exists` method, but `Get` will do.

https://github.com/darvaza-proxy/x/pull/133

**Pull request merged**
