### PR TITLE
web: Middleware factories

### PR DESCRIPTION
**Pull request by amery**
* NewMiddleware()
* NewMiddlewareError()
* NewErrorHandlerMiddleware()
* NewResolverMiddleware()
* refactor assets/EmbedFS.Middleware()

### CODE REVIEW

**Comment by amery** [comment]
introduced `NewMiddlewareError()` and `MiddlewareErrorFunc` to allow handlers to pass errors to the `ErrorHandler` easily

**Comment by amery** [comment]
`MiddlewareWithError` maybe?

**Comment by karasz** [comment]
> `NewMiddlewareWithError` maybe?

yes please

**Comment by amery** [comment]
> > `NewMiddlewareWithError` maybe?
> 
> yes please

amended and rebased

**Review by karasz — APPROVED** [review]
+1

**Comment by amery** [comment]
> +1

`darvaza.org/x/web@v0.6.1` tagged

**Pull request merged**
